### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by john-bv** [DynoCC/Dyno-Custom-Commands#11]
It's the moment we've all been waiting for, a dark theme

- [x] Add toggle for light, and dark
- [x] Add Better styling.
- [x] Add a better block / updates section.
- [x] Add current dcc website "items" to newer version

**Comment by RenderedPix** [comment]
Maybe a forum software can be linked to the website

**Comment by advaith1** [comment]
I dont really see the point of a forum

**Comment by RenderedPix** [comment]
Not an issue? Just a pr...
