### ISSUE TITLE
#signup

### ISSUE THREAD

**Issue by RenderedPix** [DynoCC/Dyno-Custom-Commands#13]
Say or any other custom command that allows Dyno to say your designated messages can be used in #signup

Banned 1 User For: ADVERTISING IN #signup

**Comment by advaith1** [comment]
fixed

**Comment by RenderedPix** [comment]
Still not fixed? http://prntscr.com/jearbu

**Comment by john-bv** [comment]
~~Being fixed momentarily.~~
Didn't get fixed, just dont use ?say :) , using it in that channel will now result in a mute.
