### ISSUE TITLE
todo: Updates to letterbox 3, add letterbox 4

### ISSUE THREAD

**Issue by advaith1** [DynoCC/Dyno-Custom-Commands#22]
- [x] Update letterbox3
- [x] Add letterbox4

**Comment by QuinnTDIP** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10134275-133553780_6-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by advaith1** [comment]
i'll update letterbox 3
I just wanna switch the center letter

**Comment by QuinnTDIP** [comment]
ok 👍

**Comment by advaith1** [comment]
@Olybear9 why did you remove it from open updates

it is an open update

**Comment by Olybear9** [comment]
its a to do and its not a bug

**Comment by advaith1** [comment]
it's an "update"

**Comment by SomeGlitchmasterGuy** [comment]
I did add [letterbox4](https://github.com/DynoCC/Dyno-Custom-Commands/blob/master/letterbox4), and I'm fairly sure I got it down, if there's any issues with what I did just contact me on Discord.
