### ISSUE TITLE
commandban and unban don't support nicknames with spaces

### ISSUE THREAD

**Issue by advaith1** [DynoCC/Dyno-Custom-Commands#23]
need to change $2 to $2+ probably
- [x] fixed commandban
- [x] fix commandunban

**Comment by advaith1** [comment]
ok so the problem is the github has the updated commands but it's not updated in the server, this only affects the dcc server but i'll leave it open until the server gets updated

**Comment by SomeGlitchmasterGuy** [comment]
Went ahead and fixed them on server
