### ISSUE TITLE
[todo] REPO - Writing down every single command, and syntax, and what it does.

### ISSUE THREAD

**Issue by Swordington** [DynoCC/Dyno-Custom-Commands#35]
Done by @TheRoboticon. Glad that's not me.

**Comment by ghost** [comment]
Unfinished as commands are being moved and deleted. I will personally update the website list.

**Comment by ghost** [comment]
The Fun Commands and Mini-Game Commands have been fully updated!

**Comment by ghost** [comment]
~~Waiting on this till I feel DCC can be more of a community.~~ I will no longer help with this issue.

**Comment by thatrelevantperson** [comment]
QuinnTDP, as TheRoboticon is no longer part of this, the issue may be removed or archived soon. 

This process may be cancelled by your request or someone doing the job.
Thanks, mel.

**Comment by DanielC7205** [comment]
Anyone still here? I would think about closing it since idk if it is completed or gave up on.

**Comment by TrixCoder** [comment]
I am here and I got a new job so I am inactive on discord. Sorry for that.

**Comment by Swordington** [comment]
Closing as Roboticon is no longer a part of DCC and nobody else has picked up the task.
