### ISSUE TITLE
[todo] WEBSITE - AMP versions of pages

### ISSUE THREAD

**Issue by advaith1** [DynoCC/Dyno-Custom-Commands#36]
⚡️ https://ampproject.org

AMP versions are places in the /amp folder.

**Comment by john-bv** [comment]
yikes

**Comment by Swordington** [comment]
Still in progress?

**Comment by Swordington** [comment]
Assuming this is effectively dead?

**Comment by Swordington** [comment]
Closing since this seems to be basically dead.
