### ISSUE TITLE
Removal of .idea folder?

### ISSUE THREAD

**Issue by Swordington** [DynoCC/Dyno-Custom-Commands#72]
It doesn't seem to serve any major purpose? Should we remove it or add it to the .gitignore?

**Comment by Fernando-Rodrigo** [comment]
It wold be a good idea to add to .gitignore

**Comment by advaith1** [comment]
it's for configuration of JetBrains IDEs, and they say to not gitignore it (except for workspace.xml, which is gitignored): https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems
