### ISSUE TITLE
Website is down - SSL issue?

### ISSUE THREAD

**Issue by rakkfalen** [DynoCC/Dyno-Custom-Commands#75]
Just wanted to let you know I get this error when trying to access dynocc.xyz
![](https://i.imgur.com/UNWNZuh.png)

**Comment by advaith1** [comment]
Thanks for reporting this! It should be fixed now, can you confirm it works for you?

**Comment by rakkfalen** [comment]
Confirmed it’s working again. Thank you, and thanks for the awesome commands!
